name: firevisor
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1+1
  cloud_firestore: ^0.14.4
  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  flutter_ringtone_player: 2.0.0
  connectivity: ^2.0.2
  wakelock: ^0.2.1+1
  firebase_auth: ^0.18.4+1
  http: ^0.12.2
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/